### ISSUE TITLE
State management for 'limit' in infinite scroll

### ISSUE THREAD

**Issue by anothermohit** [kadirahq/react-komposer#119]
I want to implement infinite scroll with react komposer in my 'Feed' container/component pair. I have multiple routes using this Feed duo (say, a home page and user profile pages).

Now, I think I am stuck at the state management for limit which is used in my Meteor subscription in Feed Container.

I know react komposer's way doesn't recommend a component changing it's own state, so what is the recommended way for an infinite scrollable component to increase the limit in its container? Even if this 'anti pattern' is to be done, should my Feed container define the 'limit' state and pass an onChange prop to the Feed component so that it can listen to the trigger in the component?

The other option that I can think of is having dynamic global states for each of the component based on its key - 
`LocalState.set(key + '_LIMIT') = LocalState.get(key + '_LIMIT') + 10`

What is the best way?

**Comment by clayne11** [comment]
You need to have the data for number of items / pages loaded at a higher abstraction level than the `react-komposer` container. Personally, I use `redux` which does a marvelous job of keeping all the state at the top level of your app so that you can access whatever data that you need at any level in the app by simply connecting to the redux store.

Alternatively, you can create a stateful component on top of the `react-komposer` container and pass down a method like `loadNextPage` and call that whenever you want to trigger another page load.

**Comment by anothermohit** [comment]
Thanks for answering. I ended up abstracting my state logic outside `react-komposer`, similar to the first solution that you have written. :)

**Comment by macrozone** [comment]
you can also `withState` from recompose https://github.com/acdlite/recompose

you can chain that into your composed function

**Comment by arunoda** [comment]
I think we can close this.
We should also document on how we can use this project with recompose.
